name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          default-branch: main
          pull-request-title-pattern: 'chore: release ${version}'
          command: manifest
          monorepo-tags: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: ${{ steps.release.outputs.release_created }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm
        if: ${{ steps.release.outputs.release_created }}

      - run: pnpm install
        if: ${{ steps.release.outputs.release_created }}

      - name: Build
        run: pnpm run build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish
        run: pnpm --filter "unminify" --filter "unpacker" --filter "cli" publish -r --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
